---
- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: Validate and reload nginx

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: Validate and reload nginx
